/*
 * JS for MyPhoneApp generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '79e1521b-563c-4029-bd7c-cd59cddeab4d';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Appery.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Appery.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "MyPhoneApp",
    "location": "#MyPhoneApp"
}];

MyPhoneApp_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {

    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'MyPhoneApp';

    /*
     * Nonvisual components
     */
    var datasources = [];

    LoginService = new Appery.DataSource(MobileService_Login, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("MyPhoneApp");
        },
        'onSuccess': function(data) {
            localStorage.setItem('locMessageText', 'Login succeeded');
        },
        'onError': function(jqXHR, textStatus, errorThrown) { /* Error callback for LoginService */
            var msg = "";

            if (textStatus != undefined) msg = msg + "\n\n" + textStatus;

            if (jqXHR) {
                msg = msg + "\n\nstatus (from jqXHT) :" + jqXHR.status;

                msg = msg + "\n\nstatusText (from jqXHT) :" + jqXHR.statusText;

                if (jqXHR.status == 200)
                //something is likely wrong with the catalog, so dump it out     
                msg = msg + "\n\nresponseText (from jqXHT) :" + jqXHR.responseText;
            }

            /* Tell user about error */
            Appery('userErrorMsg').text(msg);

            /*  alert(msg);*/
            ;
        },
        'responseMapping': [],
        'requestMapping': []
    });

    datasources.push(LoginService);

    /*
     * Events and handlers
     */

    // Before Show
    MyPhoneApp_beforeshow = function() {
        Appery.CurrentScreen = "MyPhoneApp";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_F6D4_onLoad = MyPhoneApp_onLoad = function() {
        screen_F6D4_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        MyPhoneApp_deviceEvents();
        MyPhoneApp_windowEvents();
        screen_F6D4_elementsEvents();
    }

    // screen window events
    screen_F6D4_windowEvents = MyPhoneApp_windowEvents = function() {
        $('#MyPhoneApp').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });

    }

    // device events
    MyPhoneApp_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_F6D4_elementsExtraJS = MyPhoneApp_elementsExtraJS = function() {
        // screen (MyPhoneApp) extra code

    }

    // screen elements handler
    screen_F6D4_elementsEvents = MyPhoneApp_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

    }

    $("#MyPhoneApp").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        MyPhoneApp_beforeshow();
    });

    if (runBeforeShow) {
        MyPhoneApp_beforeshow();
    } else {
        MyPhoneApp_onLoad();
    }

}

$("#MyPhoneApp").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    MyPhoneApp_js();
});